[project]
name = "spatialid"
version = "1.0.1"
requires-python = ">=3.11.5"
dependencies = [
    "pyshp==2.3.1",
    "pyproj==3.6.1",
    "pybullet==3.2.6",
    "numpy==1.26.4",
    "scikit-spatial==7.1.1",
    "pytest-mock==3.12.0"
]
